In [1]:
import numpy as np
array1 = np.array([1,2,3,4,5])
print("1D array : ",array1)
print("Datatype of 1D array: ",array1.dtype)
print("Shape of 1D array: ",array1.shape)
print("Dimension of 1D array: ",array1.ndim)
print("\n")
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D array : ",array2)
print("Datatype of 2D array: ",array2.dtype)
print("Shape of 2D array: ",array2.shape)
print("Dimension of 2D array: ",array2.ndim)
print("\n")


1D array :  [1 2 3 4 5]
Datatype of 1D array:  int32
Shape of 1D array:  (5,)
Dimension of 1D array:  1


2D array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Datatype of 2D array:  int32
Shape of 2D array:  (3, 3)
Dimension of 2D array:  2




In [2]:
import numpy as np
array_r = np.random.randint(13,25,5)
print("1D Random array : ",array_r)
array_r2 = np.random.randint(13,25,(2,2))
print("2D Random array : ",array_r2)
array_z = np.zeros(5,dtype=int)
print("2D Zero array : ",array_z)
array_z2 = np.zeros((2,2),dtype=int)
print("2D Zero array : ",array_z2)
print("Diagonal values of 2d Random array :",np.diagonal(array_r2))
print("First element of 1d Random array :",array_r[0])
print("First element of 2d Random array :",array_r2[0,0])
print("Last element of 1d Random array :",array_r[-1])
print("Last element of 2d Random array :",array_r2[-1,-1])
print("2nd row of 2d Random array :",array_r2[1,:])
print("2nd column of 2d Random array :",array_r2[:,1])
print("No of elements in 1d random array : ",array_r.size)
print("No of elements in 2d random array : ",array_r2.size)


1D Random array :  [22 21 17 20 17]
2D Random array :  [[19 21]
 [14 13]]
2D Zero array :  [0 0 0 0 0]
2D Zero array :  [[0 0]
 [0 0]]
Diagonal values of 2d Random array : [19 13]
First element of 1d Random array : 22
First element of 2d Random array : 19
Last element of 1d Random array : 17
Last element of 2d Random array : 13
2nd row of 2d Random array : [14 13]
2nd column of 2d Random array : [21 13]
No of elements in 1d random array :  5
No of elements in 2d random array :  4


In [3]:
import numpy as np
A = np.array([[10,9],[2,3]])
B = np.array([[13,14],[12,9]])
print("Matrix A :")
print(A)
print("Matrix B :")
print(B)
detA = int(np.linalg.det(A))
print("Determinant of A : ",detA)
detB = int(np.linalg.det(B))
print("Determinant of B : ",detB)
add = np.add(A,B)
print("A + B :")
print(add)
sub = np.subtract(A,B)
print("A - B :")
print(sub)
mul = np.dot(A,B)
print("A * B :")
print(mul)
div = np.divide(A,B)
print("A / B :")
print(div)
TA = np.transpose(A)
TB = np.transpose(B)
print("Transpose of A : ",TA)
print("Transpose of B : ",TB)
A_3d = np.array([A[0,0],A[1,0],0])
B_3d = np.array([B[0,0],B[1,0],0])
print("Vectors:")
print(A_3d)
print(B_3d)
print("Cross of A and B : ",np.cross(A_3d,B_3d))
print("Dot of A and B : ",np.dot(A_3d,B_3d))


Matrix A :
[[10  9]
 [ 2  3]]
Matrix B :
[[13 14]
 [12  9]]
Determinant of A :  12
Determinant of B :  -51
A + B :
[[23 23]
 [14 12]]
A - B :
[[ -3  -5]
 [-10  -6]]
A * B :
[[238 221]
 [ 62  55]]
A / B :
[[0.76923077 0.64285714]
 [0.16666667 0.33333333]]
Transpose of A :  [[10  2]
 [ 9  3]]
Transpose of B :  [[13 12]
 [14  9]]
Vectors:
[10  2  0]
[13 12  0]
Cross of A and B :  [ 0  0 94]
Dot of A and B :  154


In [4]:
import numpy as np
range1 = np.arange(13)
print("1D Range values:")
print(range1)
range2 = np.arange(13).reshape(1,13)
print("2D Range values:",range2)


1D Range values:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
2D Range values: [[ 0  1  2  3  4  5  6  7  8  9 10 11 12]]


In [5]:
import numpy as np
range1 = np.arange(26)
print("1D Range values:")
print(range1)
reshape = np.arange(26).reshape(2,13)
print("Reshaped values:",reshape)


1D Range values:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]
Reshaped values: [[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24 25]]


In [6]:
import numpy as np
from scipy import stats
arr = np.array([13,14,15,16,17,17])
min = np.min(arr)
max = np.max(arr)
sum = np.sum(arr)
mean = np.mean(arr)
median = np.median(arr)
mode = stats.mode(arr)
sd = np.std(arr)
print(f"Min: {min}")
print(f"Max: {max}")
print(f"Sum: {sum}")
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Mode: {mode}")
print(f"Std: {sd}")


Min: 13
Max: 17
Sum: 92
Mean: 15.333333333333334
Median: 15.5
Mode: ModeResult(mode=17, count=2)
Std: 1.4907119849998596


In [7]:
import numpy as np
arr = np.array([4,5,1,2,13,14,19,21,133,134,135])
mask = arr>13
filtered = arr[mask]
count13 = np.sum(mask)
print(f"Original array : {arr}")
print(f"Boolean mask : {mask}")
print(f"Filtered array : {filtered}")
print(f"Count > 13  : {count13}")


Original array : [  4   5   1   2  13  14  19  21 133 134 135]
Boolean mask : [False False False False False  True  True  True  True  True  True]
Filtered array : [ 14  19  21 133 134 135]
Count > 13  : 6


In [8]:
import numpy as np
arr = np.array([4,5,1,2,13,14,19,21,133,134,135,1333,131313,14])
indices = [1,13]
specific = arr[indices]
mask = np.ones(len(arr),dtype=bool)
mask[indices] = False
fil = arr[mask]
print(f"Original array : {arr}")
print(f"Elements at indices{indices} : {specific}")
print(f"Other : {fil}")


Original array : [     4      5      1      2     13     14     19     21    133    134
    135   1333 131313     14]
Elements at indices[1, 13] : [ 5 14]
Other : [     4      1      2     13     14     19     21    133    134    135
   1333 131313]


In [9]:
import numpy as np
student_d = np.dtype([('name','U20'),('age','i4'),('grade','U1')])
students = np.array([('Hannah',13,'O'),
                    ('Fasil',15,'A'),
                    ('Heera',16,'B')],dtype=student_d)

print("Original:")
print(students)
print("Names of students :")
print(students['name'])

print("Ages of students :")
print(students['age'])
print("Grades of students :")
print(students['grade'])
students['age'][1] = 13
students['grade'][1] = 'O'
students['name'][2] = 'Clay'
print("Modified")
print(students)


Original:
[('Hannah', 13, 'O') ('Fasil', 15, 'A') ('Heera', 16, 'B')]
Names of students :
['Hannah' 'Fasil' 'Heera']
Ages of students :
[13 15 16]
Grades of students :
['O' 'A' 'B']
Modified
[('Hannah', 13, 'O') ('Fasil', 13, 'O') ('Clay', 16, 'B')]


In [10]:
import numpy as np
X1 = np.array([2, 3, 4, 5, 6])  
X2 = np.array([1, 2, 2, 3, 3])  
y = np.array([60, 65, 70, 75, 80]) 
X = np.column_stack((np.ones(len(X1)), X1, X2))
XtX = np.dot(X.T, X)
XtX_inverse = np.linalg.inv(XtX)
XtY = np.dot(X.T, y)
theta = np.dot(XtX_inverse, XtY)
intercept, slope1, slope2 = theta
print(f"Regression Equation: y = {intercept:.2f} + ({slope1:.2f}) * x1 + ({slope2:.2f}) * x2")
print(f"Intercept (b): {intercept}")
print(f"Slope for study hours (x1): {slope1}")
print(f"Slope for practice tests (x2): {slope2}")
xnew = np.array([1, 7, 4])
predicted = np.dot(xnew, theta)
print(f"Predicted Score for Study Hours = 7, Practice Tests = 4: {predicted}")


Regression Equation: y = 50.00 + (5.00) * x1 + (-0.00) * x2
Intercept (b): 49.999999999999204
Slope for study hours (x1): 5.000000000000227
Slope for practice tests (x2): -4.547473508864641e-13
Predicted Score for Study Hours = 7, Practice Tests = 4: 84.99999999999898
